### ISSUE TITLE
Use a hash instead of a array to define the inventory (box image related)

### ISSUE THREAD

**Issue by kamuridesu** [kamuridesu/VagrantYAML#1]
Allow user to define which box to use, with two possibilities:
- Support hash and array as valid inventories
- Assert hash as the only valid inventory

In both cases, here's the syntax:

```YAML
BOX: "debian/buster64"
MACHINES:
  - NAME: "master01"
    CPU: "2"
    MEMORY: "2000"
    TYPE: "master"
    IP: 10.0.1.100

  - NAME: "worker01"
    CPU: "2"
    MEMORY: "2000"
    TYPE: "worker"
    IP: 10.0.1.101
```
